import type { CommandSpec } from "./tool-types.js";

const GENERATED_HEADER = `// This file is auto-generated by npm run refresh-spec.
// Do not edit manually.
`;

export function renderGeneratedSpec(commandSpecs: CommandSpec[]): string {
  return `${GENERATED_HEADER}
import type { CommandSpec } from "../tool-types.js";

export const OBSIDIAN_COMMAND_SPECS: CommandSpec[] = ${JSON.stringify(
    commandSpecs,
    null,
    2,
  )};
`;
}
